language: node_js
node_js:
  - node

before_install:
  - cd ./1

install:
  - cd ./frontend
  - npm install
  - cd ../backend
  - npm install

before_script:
  - cd ./1

script:
  - npm test
  - cd ../frontend
  - npm test

after_success:
  - cd ./frontend
  - npm run build
